### ISSUE TITLE
PDF not formatting correctly

### ISSUE THREAD

**Issue by BurdLab** [DarkBuffalo/ox-report#10]
Thanks for sharing a great project. However, I'm having difficulty getting the exported report to look like the one shown on the Github page. 

I installed ox-report via and load it using use-package. I created a fake minutes document with decisions and action items following the template one the Github site. This all works fine, but the pdf that is produce is formatted as a simple LaTeX article with none of the formatting of the default report. When I export as a LaTeX file, this has the standard org-mode preamble, and not the preamble contained within ox-report.el, which is what I expected to see. 

I'm likely missing something really dumb somewhere, but I've tried everything I can think of. Any help would be greatly appreciated. I've attached screenshots of the LaTeX file and pf that ox-report produces.

<img width="854" alt="Screenshot 2023-12-17 at 10 27 00 PM" src="https://github.com/DarkBuffalo/ox-report/assets/10850317/afd9190b-e402-4b6e-92cb-e0b1c0f75aaf">

<img width="855" alt="Screenshot 2023-12-17 at 10 27 17 PM" src="https://github.com/DarkBuffalo/ox-report/assets/10850317/de7b1052-2c44-4c06-8e70-3f216ed63f77">

**Comment by DarkBuffalo** [comment]
Hello @BurdLab,
Thank you for the appreciation of the project.

When you are in your org file, try invoking the ox-report-export-to-pdf command via M-x.

what is the result ?

**Comment by BurdLab** [comment]
Hi,
Interesting, it won't compile the PDF, complaining about undefined control sequence <argument> @mainlogo. Similar complaints don't happen when I compile using C-e r p (which is how I got the pdf attached in the previous message). If I
make up a logo and put the path to the png in the customization setting when loading ox-report then I get a different LaTeX error: ! LaTeX Error: There's no line to end here.   which occurs for line 291 at \fontmatter. 

I can bundle up all the files and attach them if that would help track this down.

Thanks for the help!

Adrian

**Comment by DarkBuffalo** [comment]
I think there must be an updated latex package that generates this error. 
I still have to figure out which one.

**Comment by BurdLab** [comment]
Hi, thanks for looking into this.
I may be misunderstanding what ox-report is doing, but it seems that if one produces a LaTeX file from the org file (C-e r l) then one should get the LaTeX preamble that is contained in ox-report.el (starting at line 61 of ox-report.el) in that LaTeX file. But I'm not getting that, for some reason. Instead I just get the normal LaTeX preamble that org mode produces whenever one exports to LaTeX from any org-file. So this means that none of the LaTeX formatting and new commands defined in ox-report.el are appearing in my LaTeX file. My guess is that there is something messed up with my org configuration or something messed up in the installation (which I did using package-install via Melpa). More head scratching and digging......

**Comment by DarkBuffalo** [comment]
> Hi, thanks for looking into this. I may be misunderstanding what ox-report is doing, but it seems that if one produces a LaTeX file from the org file (C-e r l) then one should get the LaTeX preamble that is contained in ox-report.el (starting at line 61 of ox-report.el) in that LaTeX file. But I'm not getting that, for some reason. Instead I just get the normal LaTeX preamble that org mode produces whenever one exports to LaTeX from any org-file. So this means that none of the LaTeX formatting and new commands defined in ox-report.el are appearing in my LaTeX file. My guess is that there is something messed up with my org configuration or something messed up in the installation (which I did using package-install via Melpa). More head scratching and digging......

try M-x ox-report-export-to-pdf-and-open
