### ISSUE TITLE
Indentation and alignment issues

### ISSUE THREAD

**Issue by natecox** [DarkBuffalo/ox-report#2]
When exporting a longer report today I noticed a couple of formatting issues:

1. Inside of a body section, the first paragraph is _not_ indented, while all subsequent paragraphs _are_. I would rather a newline be placed between paragraphs than see indentation.
1. "Project", both on the footer and on the header, is indented while other options are not. 
1. The second page of a report is _right aligned_ rather than left.

Here's a demo PDF I generated to show off the issues: 
[test.pdf](https://github.com/DarkBuffalo/ox-report/files/5211201/test.pdf)

If these are intentional rather than accidental, can we get options to turn these features on/off?

**Comment by DarkBuffalo** [comment]
> When exporting a longer report today I noticed a couple of formatting issues:
> 
>     1. Inside of a body section, the first paragraph is _not_ indented, while all subsequent paragraphs _are_. I would rather a newline be placed between paragraphs than see indentation.
for that you have to see orgmode
>     2. "Project", both on the footer and on the header, is indented while other options are not.
solved in the new update

>     3. The second page of a report is _right aligned_ rather than left.
solved in the new update

> Here's a demo PDF I generated to show off the issues:
> [test.pdf](https://github.com/DarkBuffalo/ox-report/files/5211201/test.pdf)
> 
> If these are intentional rather than accidental, can we get options to turn these features on/off?
