### ISSUE TITLE
Feature request: heading-based instead of file-based

### ISSUE THREAD

**Issue by novoid** [DarkBuffalo/ox-report#3]
Hi,
As a representative of a not so small group of Org users who [prefer large files with many headings](https://karl-voit.at/2020/05/03/current-org-files/) instead of many files with few headings, I would ask you if you do have any plans for providing this functionality based on headings as well.
This would require support for properties (`:PROPERTIES:`) instead of file-based variables (`#+foobar`). This way, somebody would be able to have notes, appointments, tasks, as well as meeting minutes in one file such as `business.org`.

**Comment by DarkBuffalo** [comment]
hi @novoid , 
thanks for your interest in the project.  
I find the idea interesting but I am starting, so I will study the question.  
If I understand correctly, the goal is to export an org file in as many PDF files as there are top level sections while using the `:properties:` to format it?

**Comment by novoid** [comment]
The goal is that you do not depend on any `#+foobar` variable which is defining some value for the whole file. If you provide an alternative for every `#+foobar` variable as a property, reports can be defined on _any_ level of hierarchy.

This way, I can have dozens of different reports within one file on any hierarchy level. Furthermore, I am free to use, e.g., `#+title` for a different purpose than for one single report title.

So moving from "one report = one org mode file" to "one org mode file can contain many different reports with different titles and similar".

**Comment by DarkBuffalo** [comment]
> The goal is that you do not depend on any `#+foobar` variable which is defining some value for the whole file. If you provide an alternative for every `#+foobar` variable as a property, reports can be defined on _any_ level of hierarchy.
> 
> This way, I can have dozens of different reports within one file on any hierarchy level. Furthermore, I am free to use, e.g., `#+title` for a different purpose than for one single report title.
> 
> So moving from "one report = one org mode file" to "one org mode file can contain many different reports with different titles and similar".

Hi @novoid 

For me it works, can you give me more details on the error :question: , please ?
Just put `EXPORT_` in front of the property and use the key combination `C-c C-e C-s r o`

Example:

```* 1er titre de niveau 1
:PROPERTIES:
:EXPORT_DATE: 01/01/2020
:EXPORT_OU: la
:EXPORT_PRESENT: Mireille tonlonto, Legros Robert
:EXPORT_INITIATEUR: Karl os
:EXPORT_PROJET: Secret project
:EXPORT_DUREE: 2H
:END:
** essai

**Comment by novoid** [comment]
Perfect - I see that the README now features also this possibility. Thanks!
