### ISSUE TITLE
Problem with fonts?

### ISSUE THREAD

**Issue by bepolymathe** [DarkBuffalo/ox-report#4]
Hi, 

Thank you for this great project. Only I have a problem that I can't solve. I have installed all the dependencies (Montserrat in particular) and I keep getting error messages. I'm not a star in LaTeX, could you tell me where it's wrong in terms of logging?
[report.log](https://github.com/DarkBuffalo/ox-report/files/5437595/report.log)
Thanks in advance. 
Have a nice day.

**Comment by DarkBuffalo** [comment]
thank you @bepolymathe for this report. 
Is a pdf file generated anyway or not at all?  if so can you send an example of pdf rendering ?
stay healthy.

**Comment by bepolymathe** [comment]
No it doesn't generate any PDF. I have an error before. 

Here is a simple example (in french) of a document that doesn't work. 
[report.zip](https://github.com/DarkBuffalo/ox-report/files/5452532/report.zip)

Thanks for your help. 

Here: Fedora 32.

**Comment by DarkBuffalo** [comment]
> No it doesn't generate any PDF. I have an error before.
> 
> Here is a simple example (in french) of a document that doesn't work.
> [report.zip](https://github.com/DarkBuffalo/ox-report/files/5452532/report.zip)
> 
> Thanks for your help.
> 
> Here: Fedora 32.

your texlive is not up to date, maybe that's it. can you update it ?
here are the details: https://tug.org/texlive/upgrade.html

**Comment by bepolymathe** [comment]
With Texlive 2020 it works. 
Thanks.
