### ISSUE TITLE
Next step --» ox-presentation ?

### ISSUE THREAD

**Issue by bepolymathe** [DarkBuffalo/ox-report#5]
Hi, 

I really liked your work on ox-report and now I want to have an ox-presentation for the slides to present during the lockdown ! 
Did you plan something like that?
Have a nice evening!

**Comment by DarkBuffalo** [comment]
> Hi, 
> 
> I really liked your work on ox-report and now I want to have an ox-presentation for the slides to present during the lockdown ! 
> Did you plan something like that?
> Have a nice evening!

Hi @bepolymathe,

I think you speak french.  open a question on the  [emacs doctor forum](https://emacs-doctor.com/forum/) and I'll get back to you.  there is an exporter included in Orgmode which is great: ox-beamer.

cordially,
